# Basic
title: iMetalk
subtitle: 北京同创智业iOS技术团队
welcome_message: <a href="http://www.immetalk.com/" target="_blank">[密语 觅友购]</a>
description: 我们是一群90后，热爱技术，喜欢分享。不局限于iOS技术本身，学习Node，了解产品，掌握跨平台开发。做好技术的同时做好产品。
creator: <a href="https://github.com/iMetalk">@iMetalk</a>

url: "https://github.com/iMetalk"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我们的项目汇总, url: 'https://lefex.github.io/2017/02/项目介绍/'}
    - {title: 关于我们, description: 关于我们描述, url: 'https://lefex.github.io/2017/02/关于我们/'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: iMetalk
    github: iMetalk
    twitter: iMetalk
    gplus: 107108267983477358170
    mail: iMetalk@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
