# Basic
title: 汽配
subtitle: 公司
welcome_message: <a href="http://www.immetalk.com/" target="_blank">[]</a>
description: 好产品。
creator: <a href="https://github.com/lefex">@Lefe_x</a>

url: "https://github.com/iMetalk"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我们的项目汇总, url: 'https://github.com/lefex'}
    - {title: 关于, description: 关于我们描述, url: 'https://github.com/lefex'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 汽配
    github: 汽配
    twitter: 汽配
    gplus: 107108267983477358170
    mail: wsyxyxs@126.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
